### ISSUE TITLE
Box fails to restart after joining the domain and renaming

### ISSUE THREAD

**Issue by wenindoubt** [mefellows/vagrant-windows-domain#17]
My box joins the domain and renames the PC, but fails to restart and apply those changes.

At this moment, I am forcing a restart with `vagrant up; vagrant reload`

My configurations are pretty barebone too:

```
  config.vm.provision :windows_domain do |domain|
    domain.domain        = tst.example.org
    domain.computer_name = devappvd-071
    domain.username      = my_username
    domain.password      = my_password
  end
```

The [error](https://pastebin.com/raw/KALXPTV0) I am receiving (it is too long to paste here)

**Comment by mefellows** [comment]
Thanks for the bug report. Off the top of my head, nothing comes to mind unfortunately.

Is this always consistent for you? Have you been able to manually perform the join - rename - restart dance?

**Comment by wenindoubt** [comment]
This does occur consistently for me, and for other Mac (Sierra) and Windows (10) devices too. I was able to manually perform the join - rename - restart via

```
$ vagrant provision; vagrant reload
```

Essentially, I just force the reboot so it'll finish joining the domain and renaming.

**Comment by mefellows** [comment]
Unless I can reproduce locally unfortunately I can't make a patch. A PR would be most welcome if you're up for it.

**Comment by mefellows** [comment]
Thanks @jwhitesoe, as mentioned above, would happily accept a PR for this :)

**Comment by jwhitesoe** [comment]
My first experience with vagrant what-so-ever, but if you can give me some hints on how to get your code in a debuggable state (or even to build it for my local vagrant) I'd gladly look at some changes.

I think the powershell is working on the rename, but somehow getting stuck in the retry loop still.  The rename definitely occurs, so it shouldnt be retrying at all -- just rebooting.!

VERBOSE: Performing the operation "Join in domain 'XXXX.com'" on target "vagrant-10".

HasSucceeded ComputerName
------------ ------------
True         vagrant-10
WARNING: The changes will take effect after you restart the computer vagrant-10.
VERBOSE: Performing the operation "Rename-Computer" on target "vagrant-10".
Rename failed, Retrying in 5 seconds...
VERBOSE: Performing the operation "Rename-Computer" on target "vagrant-10".
Rename failed, Retrying in 5 seconds...
VERBOSE: Performing the operation "Rename-Computer" on target "vagrant-10".
Rename failed, Retrying in 5 seconds...
VERBOSE: Performing the operation "Rename-Computer" on target "vagrant-10".
Rename failed, Retrying in 5 seconds...
VERBOSE: Performing the operation "Rename-Computer" on target "vagrant-10".
Rename failed, Retrying in 5 seconds...
VERBOSE: Performing the operation "Rename-Computer" on target "vagrant-10".
Rename failed the maximum number of 5 times.

 $completed = $false
	while ( -not $completed) {
		try {
			Rename-Computer <%= options_rename[:parameters] %> -Verbose -Force -ErrorAction Stop
			$completed = $true
		} catch {
			if ($retrycount -ge 5) {
				Write-Host ("Rename failed the maximum number of $retrycount times.")
				throw
			} else {
				Write-Host ("Rename failed, Retrying in 5 seconds...")
				Start-sleep -s 5
				$retrycount++
			}
		}
	}

**Comment by jwhitesoe** [comment]
`$completed = $false
	while ( -not $completed) {
		try {
			Rename-Computer <%= options_rename[:parameters] %> -Verbose -Force -ErrorAction Stop
			$completed = $true
		} catch {
			if ($retrycount -ge 5) {
				Write-Host ("Rename failed the maximum number of $retrycount times.")
				throw
			} else {
				Write-Host ("Rename failed, Retrying in 5 seconds...")
				Start-sleep -s 5
				$retrycount++
			}
		}
	}`

**Comment by alexisrosano89** [comment]
How can I set the DNS address?

**Comment by alexisrosano89** [comment]
How can I set the DNS address?

**Comment by alexisrosano89** [comment]
I get this: Computer 'vagrant-10' failed to join domain 'tecnologia.poderjudicial.gub.uy' from its current
workgroup 'WORKGROUP' with following error message: The specified domain either does not exist or could not be contacted.  FullyQualifiedErrorId : FailToJoinDomainFromWorkgroup,Microsoft.PowerShell.Commands.AddComputerCommand

**Comment by mefellows** [comment]
The best way to debug this is to attempt the rename yourself via logging into a PC and then seeing if you can do the domain rename via the UI.

If this works, then attempt using PoSH.
