### ISSUE TITLE
versioning issue

### ISSUE THREAD

**Issue by whiggs** [mefellows/vagrant-windows-domain#29]
@mefellows I see that you approved the pull request.  While I appreciate it, their seems to be a problem when actually installing the plugin using the vagrant plugin install command.  When installing the plugin, none of the changes that I made are displayed in the powershell file template.  From what I can tell, it looks like you have yet to upload the updated plugin to the ruby gems repository.  That being the case, what do you/I need to get the latest plugin pushed to the ruby gems repository?

**Comment by whiggs** [comment]
or you can just give me the rights needed to upload the updated plugin, @mefellows .  The improvements i made are useless until the updated gem is pushed to the gems repository

**Comment by mefellows** [comment]
Ah, sorry. I have a number of OSS projects and most of them have an automatic step during the build process to push to the relevant repository (in this case, rubygems). 

I can add you as an owner if you can provide your email address to me (and have signed up to Rubygems). Email address is on my bio page.

**Comment by whiggs** [comment]
I understand.  Everyone is busy.  Thank you.
